# Generated by Django 5.0.1 on 2024-02-01 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('modelo_carro', models.CharField(max_length=100)),
                ('ano_carro', models.IntegerField()),
                ('tipo_servico', models.CharField(max_length=50)),
                ('descricao_servico', models.TextField()),
                ('data_agendamento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_capa', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('km_rodados', models.FloatField()),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carro')),
            ],
        ),
    ]
