# Generated by Django 5.0.1 on 2024-02-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='imagem_capa',
            field=models.ImageField(upload_to=''),
        ),
    ]
