# Generated by Django 5.0.1 on 2024-02-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carro_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(default='Fiat', max_length=50),
        ),
    ]
