# Generated by Django 5.0.1 on 2024-02-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agendamento_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcarro',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.carro'),
        ),
    ]
